services:
  db:
    image: mariadb:11
    container_name: publishing_house_database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-testrootpassword}
      MARIADB_DATABASE: ${DB_NAME:-publishing_house_database}
      MARIADB_USER: ${DB_USER:-testuser}
      MARIADB_PASSWORD: ${DB_PASSWORD:-testpassword}
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: publishing_house_frontend
    environment:
      TEST: ${TEST:-false}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-publishing_house_database}
      DB_USER: ${DB_USER:-testuser}
      DB_PASSWORD: ${DB_PASSWORD:-testpassword}
    depends_on:
      - db